[package]
name = "pvrlib"
version = "0.1.0"
authors = ["codeonwort <codeonwort@gmail.com>"]
edition = "2018"
description = "PVR core library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
